[package]
name = "concourse-summary-rust-2018"
version = "0.1.0"
authors = ["Dave Goddard <dave@goddard.id.au>"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = "*"
serde_json = "*"
serde_yaml = "*"
serde_derive = "*"
